(0.105) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.001) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
(0.071) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = '92lloq6gs76atd910beuo8khly7o5hdo' AND "django_session"."expire_date" > '2020-09-17 11:11:35.857845'); args=('92lloq6gs76atd910beuo8khly7o5hdo', '2020-09-17 11:11:35.857845')
(0.001) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 2; args=(2,)
Exception while resolving variable 'is_popup' in template 'admin/index.html'.
Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    current = current[bit]
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\template\base.py", line 841, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\template\base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\template\base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [is_popup] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: 'jeRXxXXchwMoyP3ANLrB2aMJaIrFmvydUve4RFYcT4rtc3BYJksXU7INgDvx656L'>, 'debug': True, 'sql_queries': <function debug.<locals>.<lambda> at 0x0000014A52B288C8>, 'request': <WSGIRequest: GET '/admin/'>, 'user': <SimpleLazyObject: <User: erick>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000014A52B2C400>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0000014A528DA2B0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}}, {}, {'site_title': 'Seja bem vindo ao Gestao de Clientes', 'site_header': 'Gestao de Clientes', 'site_url': '/', 'has_permission': True, 'available_apps': [{'name': 'Autenticação e Autorização', 'app_label': 'auth', 'app_url': '/admin/auth/', 'has_module_perms': True, 'models': [{'name': 'Grupos', 'object_name': 'Group', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auth/group/', 'add_url': '/admin/auth/group/add/'}, {'name': 'Usuários', 'object_name': 'User', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auth/user/', 'add_url': '/admin/auth/user/add/'}]}, {'name': 'Clientes', 'app_label': 'clientes', 'app_url': '/admin/clientes/', 'has_module_perms': True, 'models': [{'name': 'Documentos', 'object_name': 'Documento', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/clientes/documento/', 'add_url': '/admin/clientes/documento/add/'}, {'name': 'Persons', 'object_name': 'Person', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/clientes/person/', 'add_url': '/admin/clientes/person/add/'}]}, {'name': 'Contas', 'app_label': 'account', 'app_url': '/admin/account/', 'has_module_perms': True, 'models': [{'name': 'Endereços de e-mail', 'object_name': 'EmailAddress', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/account/emailaddress/', 'add_url': '/admin/account/emailaddress/add/'}]}, {'name': 'Contas Sociais', 'app_label': 'socialaccount', 'app_url': '/admin/socialaccount/', 'has_module_perms': True, 'models': [{'name': 'Aplicativos sociais', 'object_name': 'SocialApp', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/socialaccount/socialapp/', 'add_url': '/admin/socialaccount/socialapp/add/'}, {'name': 'Contas sociais', 'object_name': 'SocialAccount', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/socialaccount/socialaccount/', 'add_url': '/admin/socialaccount/socialaccount/add/'}, {'name': 'Tokens de aplicativo social', 'object_name': 'SocialToken', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/socialaccount/socialtoken/', 'add_url': '/admin/socialaccount/socialtoken/add/'}]}, {'name': 'Produtos', 'app_label': 'produtos', 'app_url': '/admin/produtos/', 'has_module_perms': True, 'models': [{'name': 'Produtos', 'object_name': 'Produto', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/produtos/produto/', 'add_url': '/admin/produtos/produto/add/'}]}, {'name': 'Sites', 'app_label': 'sites', 'app_url': '/admin/sites/', 'has_module_perms': True, 'models': [{'name': 'Sites', 'object_name': 'Site', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/sites/site/', 'add_url': '/admin/sites/site/add/'}]}, {'name': 'Vendas', 'app_label': 'vendas', 'app_url': '/admin/vendas/', 'has_module_perms': True, 'models': [{'name': 'Itens do Pedido', 'object_name': 'ItemDoPedido', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/vendas/itemdopedido/', 'add_url': '/admin/vendas/itemdopedido/add/'}, {'name': 'Vendas', 'object_name': 'Venda', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/vendas/venda/', 'add_url': '/admin/vendas/venda/add/'}]}], 'title': 'Administracao', 'app_list': [{'name': 'Autenticação e Autorização', 'app_label': 'auth', 'app_url': '/admin/auth/', 'has_module_perms': True, 'models': [{'name': 'Grupos', 'object_name': 'Group', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auth/group/', 'add_url': '/admin/auth/group/add/'}, {'name': 'Usuários', 'object_name': 'User', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auth/user/', 'add_url': '/admin/auth/user/add/'}]}, {'name': 'Clientes', 'app_label': 'clientes', 'app_url': '/admin/clientes/', 'has_module_perms': True, 'models': [{'name': 'Documentos', 'object_name': 'Documento', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/clientes/documento/', 'add_url': '/admin/clientes/documento/add/'}, {'name': 'Persons', 'object_name': 'Person', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/clientes/person/', 'add_url': '/admin/clientes/person/add/'}]}, {'name': 'Contas', 'app_label': 'account', 'app_url': '/admin/account/', 'has_module_perms': True, 'models': [{'name': 'Endereços de e-mail', 'object_name': 'EmailAddress', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/account/emailaddress/', 'add_url': '/admin/account/emailaddress/add/'}]}, {'name': 'Contas Sociais', 'app_label': 'socialaccount', 'app_url': '/admin/socialaccount/', 'has_module_perms': True, 'models': [{'name': 'Aplicativos sociais', 'object_name': 'SocialApp', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/socialaccount/socialapp/', 'add_url': '/admin/socialaccount/socialapp/add/'}, {'name': 'Contas sociais', 'object_name': 'SocialAccount', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/socialaccount/socialaccount/', 'add_url': '/admin/socialaccount/socialaccount/add/'}, {'name': 'Tokens de aplicativo social', 'object_name': 'SocialToken', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/socialaccount/socialtoken/', 'add_url': '/admin/socialaccount/socialtoken/add/'}]}, {'name': 'Produtos', 'app_label': 'produtos', 'app_url': '/admin/produtos/', 'has_module_perms': True, 'models': [{'name': 'Produtos', 'object_name': 'Produto', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/produtos/produto/', 'add_url': '/admin/produtos/produto/add/'}]}, {'name': 'Sites', 'app_label': 'sites', 'app_url': '/admin/sites/', 'has_module_perms': True, 'models': [{'name': 'Sites', 'object_name': 'Site', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/sites/site/', 'add_url': '/admin/sites/site/add/'}]}, {'name': 'Vendas', 'app_label': 'vendas', 'app_url': '/admin/vendas/', 'has_module_perms': True, 'models': [{'name': 'Itens do Pedido', 'object_name': 'ItemDoPedido', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/vendas/itemdopedido/', 'add_url': '/admin/vendas/itemdopedido/add/'}, {'name': 'Vendas', 'object_name': 'Venda', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/vendas/venda/', 'add_url': '/admin/vendas/venda/add/'}]}], 'LANGUAGE_CODE': 'pt-br', 'LANGUAGE_BIDI': False}]
Exception while resolving variable 'is_popup' in template 'admin/index.html'.
Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    current = current[bit]
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\template\base.py", line 841, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\template\base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\template\base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [is_popup] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: 'jeRXxXXchwMoyP3ANLrB2aMJaIrFmvydUve4RFYcT4rtc3BYJksXU7INgDvx656L'>, 'debug': True, 'sql_queries': <function debug.<locals>.<lambda> at 0x0000014A52B288C8>, 'request': <WSGIRequest: GET '/admin/'>, 'user': <SimpleLazyObject: <User: erick>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000014A52B2C400>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0000014A528DA2B0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}}, {}, {'site_title': 'Seja bem vindo ao Gestao de Clientes', 'site_header': 'Gestao de Clientes', 'site_url': '/', 'has_permission': True, 'available_apps': [{'name': 'Autenticação e Autorização', 'app_label': 'auth', 'app_url': '/admin/auth/', 'has_module_perms': True, 'models': [{'name': 'Grupos', 'object_name': 'Group', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auth/group/', 'add_url': '/admin/auth/group/add/'}, {'name': 'Usuários', 'object_name': 'User', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auth/user/', 'add_url': '/admin/auth/user/add/'}]}, {'name': 'Clientes', 'app_label': 'clientes', 'app_url': '/admin/clientes/', 'has_module_perms': True, 'models': [{'name': 'Documentos', 'object_name': 'Documento', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/clientes/documento/', 'add_url': '/admin/clientes/documento/add/'}, {'name': 'Persons', 'object_name': 'Person', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/clientes/person/', 'add_url': '/admin/clientes/person/add/'}]}, {'name': 'Contas', 'app_label': 'account', 'app_url': '/admin/account/', 'has_module_perms': True, 'models': [{'name': 'Endereços de e-mail', 'object_name': 'EmailAddress', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/account/emailaddress/', 'add_url': '/admin/account/emailaddress/add/'}]}, {'name': 'Contas Sociais', 'app_label': 'socialaccount', 'app_url': '/admin/socialaccount/', 'has_module_perms': True, 'models': [{'name': 'Aplicativos sociais', 'object_name': 'SocialApp', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/socialaccount/socialapp/', 'add_url': '/admin/socialaccount/socialapp/add/'}, {'name': 'Contas sociais', 'object_name': 'SocialAccount', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/socialaccount/socialaccount/', 'add_url': '/admin/socialaccount/socialaccount/add/'}, {'name': 'Tokens de aplicativo social', 'object_name': 'SocialToken', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/socialaccount/socialtoken/', 'add_url': '/admin/socialaccount/socialtoken/add/'}]}, {'name': 'Produtos', 'app_label': 'produtos', 'app_url': '/admin/produtos/', 'has_module_perms': True, 'models': [{'name': 'Produtos', 'object_name': 'Produto', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/produtos/produto/', 'add_url': '/admin/produtos/produto/add/'}]}, {'name': 'Sites', 'app_label': 'sites', 'app_url': '/admin/sites/', 'has_module_perms': True, 'models': [{'name': 'Sites', 'object_name': 'Site', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/sites/site/', 'add_url': '/admin/sites/site/add/'}]}, {'name': 'Vendas', 'app_label': 'vendas', 'app_url': '/admin/vendas/', 'has_module_perms': True, 'models': [{'name': 'Itens do Pedido', 'object_name': 'ItemDoPedido', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/vendas/itemdopedido/', 'add_url': '/admin/vendas/itemdopedido/add/'}, {'name': 'Vendas', 'object_name': 'Venda', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/vendas/venda/', 'add_url': '/admin/vendas/venda/add/'}]}], 'title': 'Administracao', 'app_list': [{'name': 'Autenticação e Autorização', 'app_label': 'auth', 'app_url': '/admin/auth/', 'has_module_perms': True, 'models': [{'name': 'Grupos', 'object_name': 'Group', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auth/group/', 'add_url': '/admin/auth/group/add/'}, {'name': 'Usuários', 'object_name': 'User', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auth/user/', 'add_url': '/admin/auth/user/add/'}]}, {'name': 'Clientes', 'app_label': 'clientes', 'app_url': '/admin/clientes/', 'has_module_perms': True, 'models': [{'name': 'Documentos', 'object_name': 'Documento', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/clientes/documento/', 'add_url': '/admin/clientes/documento/add/'}, {'name': 'Persons', 'object_name': 'Person', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/clientes/person/', 'add_url': '/admin/clientes/person/add/'}]}, {'name': 'Contas', 'app_label': 'account', 'app_url': '/admin/account/', 'has_module_perms': True, 'models': [{'name': 'Endereços de e-mail', 'object_name': 'EmailAddress', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/account/emailaddress/', 'add_url': '/admin/account/emailaddress/add/'}]}, {'name': 'Contas Sociais', 'app_label': 'socialaccount', 'app_url': '/admin/socialaccount/', 'has_module_perms': True, 'models': [{'name': 'Aplicativos sociais', 'object_name': 'SocialApp', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/socialaccount/socialapp/', 'add_url': '/admin/socialaccount/socialapp/add/'}, {'name': 'Contas sociais', 'object_name': 'SocialAccount', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/socialaccount/socialaccount/', 'add_url': '/admin/socialaccount/socialaccount/add/'}, {'name': 'Tokens de aplicativo social', 'object_name': 'SocialToken', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/socialaccount/socialtoken/', 'add_url': '/admin/socialaccount/socialtoken/add/'}]}, {'name': 'Produtos', 'app_label': 'produtos', 'app_url': '/admin/produtos/', 'has_module_perms': True, 'models': [{'name': 'Produtos', 'object_name': 'Produto', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/produtos/produto/', 'add_url': '/admin/produtos/produto/add/'}]}, {'name': 'Sites', 'app_label': 'sites', 'app_url': '/admin/sites/', 'has_module_perms': True, 'models': [{'name': 'Sites', 'object_name': 'Site', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/sites/site/', 'add_url': '/admin/sites/site/add/'}]}, {'name': 'Vendas', 'app_label': 'vendas', 'app_url': '/admin/vendas/', 'has_module_perms': True, 'models': [{'name': 'Itens do Pedido', 'object_name': 'ItemDoPedido', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/vendas/itemdopedido/', 'add_url': '/admin/vendas/itemdopedido/add/'}, {'name': 'Vendas', 'object_name': 'Venda', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/vendas/venda/', 'add_url': '/admin/vendas/venda/add/'}]}], 'LANGUAGE_CODE': 'pt-br', 'LANGUAGE_BIDI': False}]
(0.039) SELECT "django_admin_log"."id", "django_admin_log"."action_time", "django_admin_log"."user_id", "django_admin_log"."content_type_id", "django_admin_log"."object_id", "django_admin_log"."object_repr", "django_admin_log"."action_flag", "django_admin_log"."change_message", "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined", "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_admin_log" INNER JOIN "auth_user" ON ("django_admin_log"."user_id" = "auth_user"."id") LEFT OUTER JOIN "django_content_type" ON ("django_admin_log"."content_type_id" = "django_content_type"."id") WHERE "django_admin_log"."user_id" = 2 ORDER BY "django_admin_log"."action_time" DESC LIMIT 10; args=(2,)
(0.000) BEGIN; args=None
(0.047) UPDATE "django_session" SET "session_data" = 'OTI2OGQzMTJmODY3ODYyNTk2NWQ3NGIyYTllZGQ2ZDIwZmMzNjdiMjp7Im1lc3NhZ2UiOiJPbGEgZXJpY2ssIGJvbSBkaWEhIiwiX2F1dGhfdXNlcl9pZCI6IjIiLCJfYXV0aF91c2VyX2JhY2tlbmQiOiJkamFuZ28uY29udHJpYi5hdXRoLmJhY2tlbmRzLk1vZGVsQmFja2VuZCIsIl9hdXRoX3VzZXJfaGFzaCI6IjJmMjNhNzRlNWY3ODIxNTc2MGNjYmU5Njc4ZDczN2I1NGZmYmMxZmEifQ==', "expire_date" = '2020-10-01 11:11:37.192768' WHERE "django_session"."session_key" = '92lloq6gs76atd910beuo8khly7o5hdo'; args=('OTI2OGQzMTJmODY3ODYyNTk2NWQ3NGIyYTllZGQ2ZDIwZmMzNjdiMjp7Im1lc3NhZ2UiOiJPbGEgZXJpY2ssIGJvbSBkaWEhIiwiX2F1dGhfdXNlcl9pZCI6IjIiLCJfYXV0aF91c2VyX2JhY2tlbmQiOiJkamFuZ28uY29udHJpYi5hdXRoLmJhY2tlbmRzLk1vZGVsQmFja2VuZCIsIl9hdXRoX3VzZXJfaGFzaCI6IjJmMjNhNzRlNWY3ODIxNTc2MGNjYmU5Njc4ZDczN2I1NGZmYmMxZmEifQ==', '2020-10-01 11:11:37.192768', '92lloq6gs76atd910beuo8khly7o5hdo')
"GET /admin/ HTTP/1.1" 200 20911
"GET /static/admin/css/fonts.css HTTP/1.1" 200 423
"GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 81348
"GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 80304
"GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 82564
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\urls\resolvers.py", line 523, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <module 'debug_toolbar.toolbar' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\debug_toolbar\\toolbar.py'> (djdt:djdt) '__debug__/'>], [<URLResolver <module 'home.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\home\\urls.py'> (None:None) ''>, <URLPattern '' [name='home']>], [<URLResolver <module 'home.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\home\\urls.py'> (None:None) ''>, <URLPattern 'logout/' [name='logout']>], [<URLResolver <module 'home.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\home\\urls.py'> (None:None) ''>, <URLPattern 'home2/'>], [<URLResolver <module 'home.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\home\\urls.py'> (None:None) ''>, <URLPattern 'home3/'>], [<URLResolver <module 'home.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\home\\urls.py'> (None:None) ''>, <URLPattern 'hello/'>], [<URLResolver <module 'clientes.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\clientes\\urls.py'> (None:None) 'clientes/'>], [<URLResolver <module 'vendas.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\vendas\\urls.py'> (None:None) 'vendas/'>], [<URLResolver <module 'produtos.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\produtos\\urls.py'> (None:None) 'produtos/'>], [<URLPattern 'login/' [name='login']>], [<URLResolver <URLPattern list> (admin:admin) 'admin/'>], [<URLResolver <module 'allauth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\allauth\\urls.py'> (None:None) 'accounts/'>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'login/' [name='login']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'logout/' [name='logout']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'password_change/' [name='password_change']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'password_change/done/' [name='password_change_done']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'password_reset/' [name='password_reset']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'password_reset/done/' [name='password_reset_done']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'reset/<uidb64>/<token>/' [name='password_reset_confirm']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'reset/done/' [name='password_reset_complete']>], [<URLPattern '^media\/(?P<path>.*)$'>]], 'path': 'favicon.ico'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\template\base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\template\base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <module 'debug_toolbar.toolbar' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\debug_toolbar\\toolbar.py'> (djdt:djdt) '__debug__/'>
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\urls\resolvers.py", line 523, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <module 'debug_toolbar.toolbar' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\debug_toolbar\\toolbar.py'> (djdt:djdt) '__debug__/'>], [<URLResolver <module 'home.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\home\\urls.py'> (None:None) ''>, <URLPattern '' [name='home']>], [<URLResolver <module 'home.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\home\\urls.py'> (None:None) ''>, <URLPattern 'logout/' [name='logout']>], [<URLResolver <module 'home.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\home\\urls.py'> (None:None) ''>, <URLPattern 'home2/'>], [<URLResolver <module 'home.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\home\\urls.py'> (None:None) ''>, <URLPattern 'home3/'>], [<URLResolver <module 'home.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\home\\urls.py'> (None:None) ''>, <URLPattern 'hello/'>], [<URLResolver <module 'clientes.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\clientes\\urls.py'> (None:None) 'clientes/'>], [<URLResolver <module 'vendas.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\vendas\\urls.py'> (None:None) 'vendas/'>], [<URLResolver <module 'produtos.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\produtos\\urls.py'> (None:None) 'produtos/'>], [<URLPattern 'login/' [name='login']>], [<URLResolver <URLPattern list> (admin:admin) 'admin/'>], [<URLResolver <module 'allauth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\allauth\\urls.py'> (None:None) 'accounts/'>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'login/' [name='login']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'logout/' [name='logout']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'password_change/' [name='password_change']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'password_change/done/' [name='password_change_done']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'password_reset/' [name='password_reset']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'password_reset/done/' [name='password_reset_done']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'reset/<uidb64>/<token>/' [name='password_reset_confirm']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'reset/done/' [name='password_reset_complete']>], [<URLPattern '^media\/(?P<path>.*)$'>]], 'path': 'favicon.ico'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\template\base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\template\base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <module 'clientes.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\clientes\\urls.py'> (None:None) 'clientes/'>
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\urls\resolvers.py", line 523, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <module 'debug_toolbar.toolbar' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\debug_toolbar\\toolbar.py'> (djdt:djdt) '__debug__/'>], [<URLResolver <module 'home.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\home\\urls.py'> (None:None) ''>, <URLPattern '' [name='home']>], [<URLResolver <module 'home.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\home\\urls.py'> (None:None) ''>, <URLPattern 'logout/' [name='logout']>], [<URLResolver <module 'home.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\home\\urls.py'> (None:None) ''>, <URLPattern 'home2/'>], [<URLResolver <module 'home.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\home\\urls.py'> (None:None) ''>, <URLPattern 'home3/'>], [<URLResolver <module 'home.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\home\\urls.py'> (None:None) ''>, <URLPattern 'hello/'>], [<URLResolver <module 'clientes.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\clientes\\urls.py'> (None:None) 'clientes/'>], [<URLResolver <module 'vendas.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\vendas\\urls.py'> (None:None) 'vendas/'>], [<URLResolver <module 'produtos.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\produtos\\urls.py'> (None:None) 'produtos/'>], [<URLPattern 'login/' [name='login']>], [<URLResolver <URLPattern list> (admin:admin) 'admin/'>], [<URLResolver <module 'allauth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\allauth\\urls.py'> (None:None) 'accounts/'>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'login/' [name='login']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'logout/' [name='logout']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'password_change/' [name='password_change']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'password_change/done/' [name='password_change_done']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'password_reset/' [name='password_reset']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'password_reset/done/' [name='password_reset_done']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'reset/<uidb64>/<token>/' [name='password_reset_confirm']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'reset/done/' [name='password_reset_complete']>], [<URLPattern '^media\/(?P<path>.*)$'>]], 'path': 'favicon.ico'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\template\base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\template\base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <module 'vendas.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\vendas\\urls.py'> (None:None) 'vendas/'>
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\urls\resolvers.py", line 523, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <module 'debug_toolbar.toolbar' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\debug_toolbar\\toolbar.py'> (djdt:djdt) '__debug__/'>], [<URLResolver <module 'home.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\home\\urls.py'> (None:None) ''>, <URLPattern '' [name='home']>], [<URLResolver <module 'home.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\home\\urls.py'> (None:None) ''>, <URLPattern 'logout/' [name='logout']>], [<URLResolver <module 'home.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\home\\urls.py'> (None:None) ''>, <URLPattern 'home2/'>], [<URLResolver <module 'home.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\home\\urls.py'> (None:None) ''>, <URLPattern 'home3/'>], [<URLResolver <module 'home.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\home\\urls.py'> (None:None) ''>, <URLPattern 'hello/'>], [<URLResolver <module 'clientes.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\clientes\\urls.py'> (None:None) 'clientes/'>], [<URLResolver <module 'vendas.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\vendas\\urls.py'> (None:None) 'vendas/'>], [<URLResolver <module 'produtos.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\produtos\\urls.py'> (None:None) 'produtos/'>], [<URLPattern 'login/' [name='login']>], [<URLResolver <URLPattern list> (admin:admin) 'admin/'>], [<URLResolver <module 'allauth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\allauth\\urls.py'> (None:None) 'accounts/'>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'login/' [name='login']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'logout/' [name='logout']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'password_change/' [name='password_change']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'password_change/done/' [name='password_change_done']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'password_reset/' [name='password_reset']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'password_reset/done/' [name='password_reset_done']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'reset/<uidb64>/<token>/' [name='password_reset_confirm']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'reset/done/' [name='password_reset_complete']>], [<URLPattern '^media\/(?P<path>.*)$'>]], 'path': 'favicon.ico'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\template\base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\template\base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <module 'produtos.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\produtos\\urls.py'> (None:None) 'produtos/'>
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\urls\resolvers.py", line 523, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <module 'debug_toolbar.toolbar' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\debug_toolbar\\toolbar.py'> (djdt:djdt) '__debug__/'>], [<URLResolver <module 'home.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\home\\urls.py'> (None:None) ''>, <URLPattern '' [name='home']>], [<URLResolver <module 'home.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\home\\urls.py'> (None:None) ''>, <URLPattern 'logout/' [name='logout']>], [<URLResolver <module 'home.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\home\\urls.py'> (None:None) ''>, <URLPattern 'home2/'>], [<URLResolver <module 'home.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\home\\urls.py'> (None:None) ''>, <URLPattern 'home3/'>], [<URLResolver <module 'home.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\home\\urls.py'> (None:None) ''>, <URLPattern 'hello/'>], [<URLResolver <module 'clientes.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\clientes\\urls.py'> (None:None) 'clientes/'>], [<URLResolver <module 'vendas.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\vendas\\urls.py'> (None:None) 'vendas/'>], [<URLResolver <module 'produtos.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\produtos\\urls.py'> (None:None) 'produtos/'>], [<URLPattern 'login/' [name='login']>], [<URLResolver <URLPattern list> (admin:admin) 'admin/'>], [<URLResolver <module 'allauth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\allauth\\urls.py'> (None:None) 'accounts/'>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'login/' [name='login']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'logout/' [name='logout']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'password_change/' [name='password_change']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'password_change/done/' [name='password_change_done']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'password_reset/' [name='password_reset']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'password_reset/done/' [name='password_reset_done']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'reset/<uidb64>/<token>/' [name='password_reset_confirm']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'reset/done/' [name='password_reset_complete']>], [<URLPattern '^media\/(?P<path>.*)$'>]], 'path': 'favicon.ico'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\template\base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\template\base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <URLPattern list> (admin:admin) 'admin/'>
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\urls\resolvers.py", line 523, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <module 'debug_toolbar.toolbar' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\debug_toolbar\\toolbar.py'> (djdt:djdt) '__debug__/'>], [<URLResolver <module 'home.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\home\\urls.py'> (None:None) ''>, <URLPattern '' [name='home']>], [<URLResolver <module 'home.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\home\\urls.py'> (None:None) ''>, <URLPattern 'logout/' [name='logout']>], [<URLResolver <module 'home.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\home\\urls.py'> (None:None) ''>, <URLPattern 'home2/'>], [<URLResolver <module 'home.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\home\\urls.py'> (None:None) ''>, <URLPattern 'home3/'>], [<URLResolver <module 'home.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\home\\urls.py'> (None:None) ''>, <URLPattern 'hello/'>], [<URLResolver <module 'clientes.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\clientes\\urls.py'> (None:None) 'clientes/'>], [<URLResolver <module 'vendas.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\vendas\\urls.py'> (None:None) 'vendas/'>], [<URLResolver <module 'produtos.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\produtos\\urls.py'> (None:None) 'produtos/'>], [<URLPattern 'login/' [name='login']>], [<URLResolver <URLPattern list> (admin:admin) 'admin/'>], [<URLResolver <module 'allauth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\allauth\\urls.py'> (None:None) 'accounts/'>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'login/' [name='login']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'logout/' [name='logout']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'password_change/' [name='password_change']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'password_change/done/' [name='password_change_done']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'password_reset/' [name='password_reset']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'password_reset/done/' [name='password_reset_done']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'reset/<uidb64>/<token>/' [name='password_reset_confirm']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'reset/done/' [name='password_reset_complete']>], [<URLPattern '^media\/(?P<path>.*)$'>]], 'path': 'favicon.ico'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\template\base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\template\base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <module 'allauth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\allauth\\urls.py'> (None:None) 'accounts/'>
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = '92lloq6gs76atd910beuo8khly7o5hdo' AND "django_session"."expire_date" > '2020-09-17 11:11:38.711496'); args=('92lloq6gs76atd910beuo8khly7o5hdo', '2020-09-17 11:11:38.711496')
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 14188
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = '92lloq6gs76atd910beuo8khly7o5hdo' AND "django_session"."expire_date" > '2020-09-17 11:12:04.320685'); args=('92lloq6gs76atd910beuo8khly7o5hdo', '2020-09-17 11:12:04.320685')
(0.000) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 2; args=(2,)
Acessaram a listagem de vendas
(0.024) SELECT "vendas_venda"."id", "vendas_venda"."numero", "vendas_venda"."valor", "vendas_venda"."desconto", "vendas_venda"."impostos", "vendas_venda"."pessoa_id", "vendas_venda"."nfe_emitida" FROM "vendas_venda"; args=()
(0.000) BEGIN; args=None
(0.002) UPDATE "django_session" SET "session_data" = 'OTI2OGQzMTJmODY3ODYyNTk2NWQ3NGIyYTllZGQ2ZDIwZmMzNjdiMjp7Im1lc3NhZ2UiOiJPbGEgZXJpY2ssIGJvbSBkaWEhIiwiX2F1dGhfdXNlcl9pZCI6IjIiLCJfYXV0aF91c2VyX2JhY2tlbmQiOiJkamFuZ28uY29udHJpYi5hdXRoLmJhY2tlbmRzLk1vZGVsQmFja2VuZCIsIl9hdXRoX3VzZXJfaGFzaCI6IjJmMjNhNzRlNWY3ODIxNTc2MGNjYmU5Njc4ZDczN2I1NGZmYmMxZmEifQ==', "expire_date" = '2020-10-01 11:12:04.707677' WHERE "django_session"."session_key" = '92lloq6gs76atd910beuo8khly7o5hdo'; args=('OTI2OGQzMTJmODY3ODYyNTk2NWQ3NGIyYTllZGQ2ZDIwZmMzNjdiMjp7Im1lc3NhZ2UiOiJPbGEgZXJpY2ssIGJvbSBkaWEhIiwiX2F1dGhfdXNlcl9pZCI6IjIiLCJfYXV0aF91c2VyX2JhY2tlbmQiOiJkamFuZ28uY29udHJpYi5hdXRoLmJhY2tlbmRzLk1vZGVsQmFja2VuZCIsIl9hdXRoX3VzZXJfaGFzaCI6IjJmMjNhNzRlNWY3ODIxNTc2MGNjYmU5Njc4ZDczN2I1NGZmYmMxZmEifQ==', '2020-10-01 11:12:04.707677', '92lloq6gs76atd910beuo8khly7o5hdo')
"GET /vendas/ HTTP/1.1" 200 18619
"GET /static/style.css HTTP/1.1" 304 0
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\urls\resolvers.py", line 523, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <module 'debug_toolbar.toolbar' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\debug_toolbar\\toolbar.py'> (djdt:djdt) '__debug__/'>], [<URLResolver <module 'home.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\home\\urls.py'> (None:None) ''>, <URLPattern '' [name='home']>], [<URLResolver <module 'home.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\home\\urls.py'> (None:None) ''>, <URLPattern 'logout/' [name='logout']>], [<URLResolver <module 'home.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\home\\urls.py'> (None:None) ''>, <URLPattern 'home2/'>], [<URLResolver <module 'home.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\home\\urls.py'> (None:None) ''>, <URLPattern 'home3/'>], [<URLResolver <module 'home.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\home\\urls.py'> (None:None) ''>, <URLPattern 'hello/'>], [<URLResolver <module 'clientes.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\clientes\\urls.py'> (None:None) 'clientes/'>], [<URLResolver <module 'vendas.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\vendas\\urls.py'> (None:None) 'vendas/'>, <URLPattern '' [name='lista-vendas']>], [<URLResolver <module 'vendas.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\vendas\\urls.py'> (None:None) 'vendas/'>, <URLPattern 'novo-pedido/' [name='novo-pedido']>], [<URLResolver <module 'vendas.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\vendas\\urls.py'> (None:None) 'vendas/'>, <URLPattern 'novo-item-pedido/<int:venda>' [name='novo-item-pedido']>], [<URLResolver <module 'vendas.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\vendas\\urls.py'> (None:None) 'vendas/'>, <URLPattern 'edit-pedido/<int:venda>/' [name='edit-pedido']>], [<URLResolver <module 'vendas.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\vendas\\urls.py'> (None:None) 'vendas/'>, <URLPattern 'delete-pedido/<int:venda>/' [name='delete-pedido']>], [<URLResolver <module 'vendas.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\vendas\\urls.py'> (None:None) 'vendas/'>, <URLPattern 'delete-item-pedido/<int:item>/' [name='delete-item-pedido']>], [<URLResolver <module 'vendas.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\vendas\\urls.py'> (None:None) 'vendas/'>, <URLPattern 'edit-item-pedido/<int:item>/' [name='edit-item-pedido']>], [<URLResolver <module 'vendas.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\vendas\\urls.py'> (None:None) 'vendas/'>, <URLPattern 'dashboard/' [name='dashboard']>], [<URLResolver <module 'produtos.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\produtos\\urls.py'> (None:None) 'produtos/'>], [<URLPattern 'login/' [name='login']>], [<URLResolver <URLPattern list> (admin:admin) 'admin/'>], [<URLResolver <module 'allauth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\allauth\\urls.py'> (None:None) 'accounts/'>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'login/' [name='login']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'logout/' [name='logout']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'password_change/' [name='password_change']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'password_change/done/' [name='password_change_done']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'password_reset/' [name='password_reset']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'password_reset/done/' [name='password_reset_done']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'reset/<uidb64>/<token>/' [name='password_reset_confirm']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'reset/done/' [name='password_reset_complete']>], [<URLPattern '^media\/(?P<path>.*)$'>]], 'path': 'vendas/lista-vendas'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\template\base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\template\base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <module 'debug_toolbar.toolbar' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\debug_toolbar\\toolbar.py'> (djdt:djdt) '__debug__/'>
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\urls\resolvers.py", line 523, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <module 'debug_toolbar.toolbar' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\debug_toolbar\\toolbar.py'> (djdt:djdt) '__debug__/'>], [<URLResolver <module 'home.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\home\\urls.py'> (None:None) ''>, <URLPattern '' [name='home']>], [<URLResolver <module 'home.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\home\\urls.py'> (None:None) ''>, <URLPattern 'logout/' [name='logout']>], [<URLResolver <module 'home.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\home\\urls.py'> (None:None) ''>, <URLPattern 'home2/'>], [<URLResolver <module 'home.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\home\\urls.py'> (None:None) ''>, <URLPattern 'home3/'>], [<URLResolver <module 'home.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\home\\urls.py'> (None:None) ''>, <URLPattern 'hello/'>], [<URLResolver <module 'clientes.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\clientes\\urls.py'> (None:None) 'clientes/'>], [<URLResolver <module 'vendas.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\vendas\\urls.py'> (None:None) 'vendas/'>, <URLPattern '' [name='lista-vendas']>], [<URLResolver <module 'vendas.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\vendas\\urls.py'> (None:None) 'vendas/'>, <URLPattern 'novo-pedido/' [name='novo-pedido']>], [<URLResolver <module 'vendas.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\vendas\\urls.py'> (None:None) 'vendas/'>, <URLPattern 'novo-item-pedido/<int:venda>' [name='novo-item-pedido']>], [<URLResolver <module 'vendas.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\vendas\\urls.py'> (None:None) 'vendas/'>, <URLPattern 'edit-pedido/<int:venda>/' [name='edit-pedido']>], [<URLResolver <module 'vendas.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\vendas\\urls.py'> (None:None) 'vendas/'>, <URLPattern 'delete-pedido/<int:venda>/' [name='delete-pedido']>], [<URLResolver <module 'vendas.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\vendas\\urls.py'> (None:None) 'vendas/'>, <URLPattern 'delete-item-pedido/<int:item>/' [name='delete-item-pedido']>], [<URLResolver <module 'vendas.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\vendas\\urls.py'> (None:None) 'vendas/'>, <URLPattern 'edit-item-pedido/<int:item>/' [name='edit-item-pedido']>], [<URLResolver <module 'vendas.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\vendas\\urls.py'> (None:None) 'vendas/'>, <URLPattern 'dashboard/' [name='dashboard']>], [<URLResolver <module 'produtos.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\produtos\\urls.py'> (None:None) 'produtos/'>], [<URLPattern 'login/' [name='login']>], [<URLResolver <URLPattern list> (admin:admin) 'admin/'>], [<URLResolver <module 'allauth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\allauth\\urls.py'> (None:None) 'accounts/'>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'login/' [name='login']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'logout/' [name='logout']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'password_change/' [name='password_change']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'password_change/done/' [name='password_change_done']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'password_reset/' [name='password_reset']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'password_reset/done/' [name='password_reset_done']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'reset/<uidb64>/<token>/' [name='password_reset_confirm']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'reset/done/' [name='password_reset_complete']>], [<URLPattern '^media\/(?P<path>.*)$'>]], 'path': 'vendas/lista-vendas'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\template\base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\template\base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <module 'clientes.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\clientes\\urls.py'> (None:None) 'clientes/'>
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\urls\resolvers.py", line 523, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <module 'debug_toolbar.toolbar' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\debug_toolbar\\toolbar.py'> (djdt:djdt) '__debug__/'>], [<URLResolver <module 'home.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\home\\urls.py'> (None:None) ''>, <URLPattern '' [name='home']>], [<URLResolver <module 'home.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\home\\urls.py'> (None:None) ''>, <URLPattern 'logout/' [name='logout']>], [<URLResolver <module 'home.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\home\\urls.py'> (None:None) ''>, <URLPattern 'home2/'>], [<URLResolver <module 'home.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\home\\urls.py'> (None:None) ''>, <URLPattern 'home3/'>], [<URLResolver <module 'home.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\home\\urls.py'> (None:None) ''>, <URLPattern 'hello/'>], [<URLResolver <module 'clientes.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\clientes\\urls.py'> (None:None) 'clientes/'>], [<URLResolver <module 'vendas.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\vendas\\urls.py'> (None:None) 'vendas/'>, <URLPattern '' [name='lista-vendas']>], [<URLResolver <module 'vendas.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\vendas\\urls.py'> (None:None) 'vendas/'>, <URLPattern 'novo-pedido/' [name='novo-pedido']>], [<URLResolver <module 'vendas.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\vendas\\urls.py'> (None:None) 'vendas/'>, <URLPattern 'novo-item-pedido/<int:venda>' [name='novo-item-pedido']>], [<URLResolver <module 'vendas.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\vendas\\urls.py'> (None:None) 'vendas/'>, <URLPattern 'edit-pedido/<int:venda>/' [name='edit-pedido']>], [<URLResolver <module 'vendas.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\vendas\\urls.py'> (None:None) 'vendas/'>, <URLPattern 'delete-pedido/<int:venda>/' [name='delete-pedido']>], [<URLResolver <module 'vendas.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\vendas\\urls.py'> (None:None) 'vendas/'>, <URLPattern 'delete-item-pedido/<int:item>/' [name='delete-item-pedido']>], [<URLResolver <module 'vendas.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\vendas\\urls.py'> (None:None) 'vendas/'>, <URLPattern 'edit-item-pedido/<int:item>/' [name='edit-item-pedido']>], [<URLResolver <module 'vendas.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\vendas\\urls.py'> (None:None) 'vendas/'>, <URLPattern 'dashboard/' [name='dashboard']>], [<URLResolver <module 'produtos.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\produtos\\urls.py'> (None:None) 'produtos/'>], [<URLPattern 'login/' [name='login']>], [<URLResolver <URLPattern list> (admin:admin) 'admin/'>], [<URLResolver <module 'allauth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\allauth\\urls.py'> (None:None) 'accounts/'>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'login/' [name='login']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'logout/' [name='logout']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'password_change/' [name='password_change']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'password_change/done/' [name='password_change_done']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'password_reset/' [name='password_reset']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'password_reset/done/' [name='password_reset_done']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'reset/<uidb64>/<token>/' [name='password_reset_confirm']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'reset/done/' [name='password_reset_complete']>], [<URLPattern '^media\/(?P<path>.*)$'>]], 'path': 'vendas/lista-vendas'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\template\base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\template\base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <module 'produtos.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\produtos\\urls.py'> (None:None) 'produtos/'>
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\urls\resolvers.py", line 523, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <module 'debug_toolbar.toolbar' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\debug_toolbar\\toolbar.py'> (djdt:djdt) '__debug__/'>], [<URLResolver <module 'home.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\home\\urls.py'> (None:None) ''>, <URLPattern '' [name='home']>], [<URLResolver <module 'home.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\home\\urls.py'> (None:None) ''>, <URLPattern 'logout/' [name='logout']>], [<URLResolver <module 'home.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\home\\urls.py'> (None:None) ''>, <URLPattern 'home2/'>], [<URLResolver <module 'home.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\home\\urls.py'> (None:None) ''>, <URLPattern 'home3/'>], [<URLResolver <module 'home.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\home\\urls.py'> (None:None) ''>, <URLPattern 'hello/'>], [<URLResolver <module 'clientes.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\clientes\\urls.py'> (None:None) 'clientes/'>], [<URLResolver <module 'vendas.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\vendas\\urls.py'> (None:None) 'vendas/'>, <URLPattern '' [name='lista-vendas']>], [<URLResolver <module 'vendas.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\vendas\\urls.py'> (None:None) 'vendas/'>, <URLPattern 'novo-pedido/' [name='novo-pedido']>], [<URLResolver <module 'vendas.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\vendas\\urls.py'> (None:None) 'vendas/'>, <URLPattern 'novo-item-pedido/<int:venda>' [name='novo-item-pedido']>], [<URLResolver <module 'vendas.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\vendas\\urls.py'> (None:None) 'vendas/'>, <URLPattern 'edit-pedido/<int:venda>/' [name='edit-pedido']>], [<URLResolver <module 'vendas.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\vendas\\urls.py'> (None:None) 'vendas/'>, <URLPattern 'delete-pedido/<int:venda>/' [name='delete-pedido']>], [<URLResolver <module 'vendas.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\vendas\\urls.py'> (None:None) 'vendas/'>, <URLPattern 'delete-item-pedido/<int:item>/' [name='delete-item-pedido']>], [<URLResolver <module 'vendas.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\vendas\\urls.py'> (None:None) 'vendas/'>, <URLPattern 'edit-item-pedido/<int:item>/' [name='edit-item-pedido']>], [<URLResolver <module 'vendas.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\vendas\\urls.py'> (None:None) 'vendas/'>, <URLPattern 'dashboard/' [name='dashboard']>], [<URLResolver <module 'produtos.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\produtos\\urls.py'> (None:None) 'produtos/'>], [<URLPattern 'login/' [name='login']>], [<URLResolver <URLPattern list> (admin:admin) 'admin/'>], [<URLResolver <module 'allauth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\allauth\\urls.py'> (None:None) 'accounts/'>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'login/' [name='login']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'logout/' [name='logout']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'password_change/' [name='password_change']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'password_change/done/' [name='password_change_done']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'password_reset/' [name='password_reset']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'password_reset/done/' [name='password_reset_done']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'reset/<uidb64>/<token>/' [name='password_reset_confirm']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'reset/done/' [name='password_reset_complete']>], [<URLPattern '^media\/(?P<path>.*)$'>]], 'path': 'vendas/lista-vendas'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\template\base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\template\base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <URLPattern list> (admin:admin) 'admin/'>
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\urls\resolvers.py", line 523, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <module 'debug_toolbar.toolbar' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\debug_toolbar\\toolbar.py'> (djdt:djdt) '__debug__/'>], [<URLResolver <module 'home.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\home\\urls.py'> (None:None) ''>, <URLPattern '' [name='home']>], [<URLResolver <module 'home.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\home\\urls.py'> (None:None) ''>, <URLPattern 'logout/' [name='logout']>], [<URLResolver <module 'home.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\home\\urls.py'> (None:None) ''>, <URLPattern 'home2/'>], [<URLResolver <module 'home.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\home\\urls.py'> (None:None) ''>, <URLPattern 'home3/'>], [<URLResolver <module 'home.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\home\\urls.py'> (None:None) ''>, <URLPattern 'hello/'>], [<URLResolver <module 'clientes.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\clientes\\urls.py'> (None:None) 'clientes/'>], [<URLResolver <module 'vendas.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\vendas\\urls.py'> (None:None) 'vendas/'>, <URLPattern '' [name='lista-vendas']>], [<URLResolver <module 'vendas.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\vendas\\urls.py'> (None:None) 'vendas/'>, <URLPattern 'novo-pedido/' [name='novo-pedido']>], [<URLResolver <module 'vendas.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\vendas\\urls.py'> (None:None) 'vendas/'>, <URLPattern 'novo-item-pedido/<int:venda>' [name='novo-item-pedido']>], [<URLResolver <module 'vendas.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\vendas\\urls.py'> (None:None) 'vendas/'>, <URLPattern 'edit-pedido/<int:venda>/' [name='edit-pedido']>], [<URLResolver <module 'vendas.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\vendas\\urls.py'> (None:None) 'vendas/'>, <URLPattern 'delete-pedido/<int:venda>/' [name='delete-pedido']>], [<URLResolver <module 'vendas.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\vendas\\urls.py'> (None:None) 'vendas/'>, <URLPattern 'delete-item-pedido/<int:item>/' [name='delete-item-pedido']>], [<URLResolver <module 'vendas.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\vendas\\urls.py'> (None:None) 'vendas/'>, <URLPattern 'edit-item-pedido/<int:item>/' [name='edit-item-pedido']>], [<URLResolver <module 'vendas.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\vendas\\urls.py'> (None:None) 'vendas/'>, <URLPattern 'dashboard/' [name='dashboard']>], [<URLResolver <module 'produtos.urls' from 'C:\\Users\\erick\\OneDrive\\Documentos\\projetos_cursos\\gestao_clientes-advanced\\src\\produtos\\urls.py'> (None:None) 'produtos/'>], [<URLPattern 'login/' [name='login']>], [<URLResolver <URLPattern list> (admin:admin) 'admin/'>], [<URLResolver <module 'allauth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\allauth\\urls.py'> (None:None) 'accounts/'>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'login/' [name='login']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'logout/' [name='logout']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'password_change/' [name='password_change']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'password_change/done/' [name='password_change_done']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'password_reset/' [name='password_reset']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'password_reset/done/' [name='password_reset_done']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'reset/<uidb64>/<token>/' [name='password_reset_confirm']>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\django\\contrib\\auth\\urls.py'> (None:None) ''>, <URLPattern 'reset/done/' [name='password_reset_complete']>], [<URLPattern '^media\/(?P<path>.*)$'>]], 'path': 'vendas/lista-vendas'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\template\base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\erick\.virtualenvs\gestao_clientes-advanced-C6lOFuyJ\lib\site-packages\django\template\base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <module 'allauth.urls' from 'C:\\Users\\erick\\.virtualenvs\\gestao_clientes-advanced-C6lOFuyJ\\lib\\site-packages\\allauth\\urls.py'> (None:None) 'accounts/'>
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = '92lloq6gs76atd910beuo8khly7o5hdo' AND "django_session"."expire_date" > '2020-09-17 11:12:08.103251'); args=('92lloq6gs76atd910beuo8khly7o5hdo', '2020-09-17 11:12:08.103251')
Not Found: /vendas/lista-vendas
"GET /vendas/lista-vendas HTTP/1.1" 404 15703
"GET /vendas HTTP/1.1" 301 0
(0.000) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = '92lloq6gs76atd910beuo8khly7o5hdo' AND "django_session"."expire_date" > '2020-09-17 11:12:30.697911'); args=('92lloq6gs76atd910beuo8khly7o5hdo', '2020-09-17 11:12:30.697911')
(0.001) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 2; args=(2,)
Acessaram a listagem de vendas
(0.001) SELECT "vendas_venda"."id", "vendas_venda"."numero", "vendas_venda"."valor", "vendas_venda"."desconto", "vendas_venda"."impostos", "vendas_venda"."pessoa_id", "vendas_venda"."nfe_emitida" FROM "vendas_venda"; args=()
(0.000) BEGIN; args=None
(0.002) UPDATE "django_session" SET "session_data" = 'OTI2OGQzMTJmODY3ODYyNTk2NWQ3NGIyYTllZGQ2ZDIwZmMzNjdiMjp7Im1lc3NhZ2UiOiJPbGEgZXJpY2ssIGJvbSBkaWEhIiwiX2F1dGhfdXNlcl9pZCI6IjIiLCJfYXV0aF91c2VyX2JhY2tlbmQiOiJkamFuZ28uY29udHJpYi5hdXRoLmJhY2tlbmRzLk1vZGVsQmFja2VuZCIsIl9hdXRoX3VzZXJfaGFzaCI6IjJmMjNhNzRlNWY3ODIxNTc2MGNjYmU5Njc4ZDczN2I1NGZmYmMxZmEifQ==', "expire_date" = '2020-10-01 11:12:30.811785' WHERE "django_session"."session_key" = '92lloq6gs76atd910beuo8khly7o5hdo'; args=('OTI2OGQzMTJmODY3ODYyNTk2NWQ3NGIyYTllZGQ2ZDIwZmMzNjdiMjp7Im1lc3NhZ2UiOiJPbGEgZXJpY2ssIGJvbSBkaWEhIiwiX2F1dGhfdXNlcl9pZCI6IjIiLCJfYXV0aF91c2VyX2JhY2tlbmQiOiJkamFuZ28uY29udHJpYi5hdXRoLmJhY2tlbmRzLk1vZGVsQmFja2VuZCIsIl9hdXRoX3VzZXJfaGFzaCI6IjJmMjNhNzRlNWY3ODIxNTc2MGNjYmU5Njc4ZDczN2I1NGZmYmMxZmEifQ==', '2020-10-01 11:12:30.811785', '92lloq6gs76atd910beuo8khly7o5hdo')
"GET /vendas/ HTTP/1.1" 200 18618
(0.002) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
(0.002) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = '92lloq6gs76atd910beuo8khly7o5hdo' AND "django_session"."expire_date" > '2020-09-17 11:14:00.350330'); args=('92lloq6gs76atd910beuo8khly7o5hdo', '2020-09-17 11:14:00.350330')
(0.002) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 2; args=(2,)
Acessaram a listagem de vendas
division by zero
(0.000) SELECT "vendas_venda"."id", "vendas_venda"."numero", "vendas_venda"."valor", "vendas_venda"."desconto", "vendas_venda"."impostos", "vendas_venda"."pessoa_id", "vendas_venda"."nfe_emitida" FROM "vendas_venda"; args=()
(0.001) BEGIN; args=None
(0.002) UPDATE "django_session" SET "session_data" = 'OTI2OGQzMTJmODY3ODYyNTk2NWQ3NGIyYTllZGQ2ZDIwZmMzNjdiMjp7Im1lc3NhZ2UiOiJPbGEgZXJpY2ssIGJvbSBkaWEhIiwiX2F1dGhfdXNlcl9pZCI6IjIiLCJfYXV0aF91c2VyX2JhY2tlbmQiOiJkamFuZ28uY29udHJpYi5hdXRoLmJhY2tlbmRzLk1vZGVsQmFja2VuZCIsIl9hdXRoX3VzZXJfaGFzaCI6IjJmMjNhNzRlNWY3ODIxNTc2MGNjYmU5Njc4ZDczN2I1NGZmYmMxZmEifQ==', "expire_date" = '2020-10-01 11:14:00.832583' WHERE "django_session"."session_key" = '92lloq6gs76atd910beuo8khly7o5hdo'; args=('OTI2OGQzMTJmODY3ODYyNTk2NWQ3NGIyYTllZGQ2ZDIwZmMzNjdiMjp7Im1lc3NhZ2UiOiJPbGEgZXJpY2ssIGJvbSBkaWEhIiwiX2F1dGhfdXNlcl9pZCI6IjIiLCJfYXV0aF91c2VyX2JhY2tlbmQiOiJkamFuZ28uY29udHJpYi5hdXRoLmJhY2tlbmRzLk1vZGVsQmFja2VuZCIsIl9hdXRoX3VzZXJfaGFzaCI6IjJmMjNhNzRlNWY3ODIxNTc2MGNjYmU5Njc4ZDczN2I1NGZmYmMxZmEifQ==', '2020-10-01 11:14:00.832583', '92lloq6gs76atd910beuo8khly7o5hdo')
"GET /vendas/ HTTP/1.1" 200 18619
